#!/usr/bin/env sh
set -eu
#
# See https://github.com/rhysd/cargo-husky#readme
#

echo "-------------------------------------------------------------------------------"
echo "Run CI steps"
echo "The following steps are also ran during   git push   command."
echo "If you want to push your changes without running CI, use   git push --no-verify"
echo "-------------------------------------------------------------------------------"

just test
