#!/bin/sh
#
# See https://github.com/rhysd/cargo-husky#readme
#

set -ex

echo "+Run CI steps"

rustc --version
cargo --version
cargo fmt --all -- --check
cargo clippy -- -D warnings
cargo build
cargo test --workspace --all-targets --bins --tests --lib --benches
cargo test --doc
RUSTDOCFLAGS="-D warnings" cargo doc --no-deps
